version: '3'

services:

  mongo-express:
    image: mongo-express
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:MongoDB!@mongo:27017/
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB!
      ME_CONFIG_BASICAUTH_USERNAME: app
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2025!
    networks:
      - app-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB!
    ports:
      - "27017:27017"
    networks:
      - app-network

networks: 
    app-network:
      driver: bridge